### ISSUE TITLE
PHPUnit test failure

### ISSUE THREAD

**Issue by mdjnelson** [moodlehq/moodle-mlbackend-python#2]
```core_analytics_prediction_testcase::test_ml_training_and_prediction with data set "no_splitting-\mlbackend_python\processor" ('\core\analytics\time_splittin...itting', 0, 1, '\mlbackend_python\processor')
moodle_exception: No results returned from the predictions processor. Check the output directory contents for more information.

/home/markn/mstorage/sm/moodle/lib/mlbackend/python/classes/processor.php:166
/home/markn/mstorage/sm/moodle/analytics/classes/model.php:713
/home/markn/mstorage/sm/moodle/analytics/tests/prediction_test.php:175
/home/markn/mstorage/sm/moodle/lib/phpunit/classes/advanced_testcase.php:80```

**Comment by dmonllao** [comment]
Thanks Mark.

This is failing because the python backend generates a log directory for each execution and in fast enough systems more than 1 action can be executed in 1 second.

We need to change this https://github.com/moodlehq/moodle-mlbackend-python/blob/master/moodlemlbackend/processor/estimator.py#L29 to use microseconds instead of https://docs.python.org/2/library/time.html#time.time or a similar solution.

**Comment by dmonllao** [comment]
Patch in 4e2cc7ae6c2a7d9fe63bd114512deff9de926e97, waiting for MDL-59988 to be reviewed to merge here.

**Comment by dmonllao** [comment]
Closing as the fix above was already integrated and release as part of 0.0.4
