### ISSUE TITLE
Moodlemlbackend package installation

### ISSUE THREAD

**Issue by vandnaik** [moodlehq/moodle-mlbackend-python#4]
When trying to install moodlemlbackend package, I am getting the following error

Could not find a version that satisfies the requirement tensorflow<1.1,>=1.0.0 (from moodlemlbackend==0.0.5) (from versions: )
No matching distribution found for tensorflow<1.1,>=1.0.0 (from moodlemlbackend==0.0.5)

Kindly advise what are the steps to be taken to resolve this error.

I know that this was an issue with an earlier version, however, I am trying to install the latest version and still getting the error.

**Comment by dmonllao** [comment]
Hi @vandnaik this issue seems unrelated to https://github.com/moodlehq/moodle-mlbackend-python/commit/2d6d5d225fd11a38dce9f0006c37f5c46a2f514c as I see that the error message includes the correct way to specify the version.

I would need more info to help you, I can see some tensorflow versions matching the required moodlemlbackend version: https://pypi.org/project/tensorflow/#history.

**Comment by dmonllao** [comment]
I've been able to install the package as specified in the docs (pip install moodlemlbackend) I'm using ubuntu 16.04 with pip 10.0.1. I just updated from pip 9.0.1 and it worked ok for what I can remember.

**Comment by vandnaik** [comment]
Hi David

I am working on Windows 10 Pro 64 bit OS, Intel Xeon CPU.

I have installed Moodle 3.5beta from https://download.moodle.org/windows/
Now I am trying to install moodlemlbackend package and got this error


![image](https://user-images.githubusercontent.com/23470460/39238493-fabfa36a-489b-11e8-8910-cfdee865885c.png)

I have tried to install Tensorflow 0.12.0 separately and then install the package but still, the error persists.

**Comment by dmonllao** [comment]
Hi @vandnaik The problem seems to be that tensorflow<1.1,>=1.0.0 packages were only released for python 2.x (https://pypi.org/project/tensorflow/1.0.1/). They started publishing pypi packages for 3.x in (https://pypi.org/project/tensorflow/1.4.0/)

So you have 2 options:
- Use python 2.x
- Compile tensorflow for python 3 from source

I am updating our setup guide to explain this. Thanks for reporting the issue. Closing it.

**Comment by sebastiangz** [comment]
sudo pip3 install moodlemlbackend==1.0.1
