### ISSUE TITLE
Is there a version of this that runs on Python 3.x?

### ISSUE THREAD

**Issue by blm-unikent** [moodlehq/moodle-mlbackend-python#8]
If I run from a Python 2.7 environment (end of life soon) I can pip install moodlemlbackend with no problem.

However, whether in a python or conda docker container or on my linux workstation I set up a Python 3.6 or 3.7 environment the dependencies require a build that fails under `pip install moodlemlbackend`

Do you have a requirements list or Python version 3+ that can run pip install and work?

**Comment by dmonllao** [comment]
Hi @blm-unikent. Thanks for creating the issue. This is in my todo list. We will bump the dependency requirements during the next months and the package will run correctly on python 2.x and 3.x. I will post an update here once done.

**Comment by dmonllao** [comment]
Hi @blm-unikent. I've just installed the current moodle-mlbackend-python package on python 3 in a docker container without further changes (The image is based on debian:stretch-slim).

The container uses python 3.5.3. However, I can't install it in a system running python 3.6.8. The package may be compatible with 3.5.3 but not with 3.6 and higher. In any case, we expect to this this during the upcoming months.

**Comment by dmonllao** [comment]
FYI: https://tracker.moodle.org/browse/MDL-66069. I propose to support python 2.7, 3.4, 3.5 and 3.6 in stable versions (Moodle 3.6 and 3.7) and to support 3.4, 3.5, 3.6 and 3.7 in master (Moodle 3.8dev).

**Comment by brianlmerritt** [comment]
Great - thanks for the update.  I can't find that item on the tracker.moodle site - is it private?

**Comment by dmonllao** [comment]
Hi @brianlmerritt, yes, it is private because it is a security MDL (there is a security bug in one of the dependencies we use).

You can see the proposed patches here
* For stables (Moodle 3.6 and 3.7) we add compatibility for python 3.6: https://github.com/moodlehq/moodle-mlbackend-python/compare/master...dmonllao:MDL-66069_stables
* For master (Moodle 3.8dev) we add compatibility for python 3.5, 3.6 and 3.7, and we drop compatibility with python 2.7 (end of life Jan 2020) https://github.com/moodlehq/moodle-mlbackend-python/compare/master...dmonllao:MDL-66069_master

**Comment by dmonllao** [comment]
Closing as #9  and #10 have been integrated.
